<?php
  // file icon map
  /* $Id: fileiconmap.inc 1830 2015-01-04 09:49:10Z hom $ */
$fileimages=array( 'application/pdf'               => 'application-pdf.png',
		   'application/vnd.ms-powerpoint' => 'application-vnd.ms-powerpoint.png',
		   'application/vnd.ms-excel'      => 'application-vnd.ms-excel.png',
		   'application/msword'            => 'icon-doc.png',
		   'application/rar'               => 'icon-rar.gif',
		   'application/x-rar-compressed'  => 'icon-rar.gif',
		   'application/x-zip-compressed'  => 'icon-zip.png',
		   'application/zip'               => 'icon-zip.png',
		   'application/vnd.oasis.opendocument.spreadsheet' => 'calc.gif',
		   'application/vnd.openxmlformats-officedocument.presentationml.presentation' =>
		   'application-vnd.ms-powerpoint.png',
		   );

?>