<?php
/**
 * @package peerweb
 * @author Pieter van den Hombergh
 * $Id: genform.php 1723 2014-01-03 08:34:59Z hom $
 * Genform generates a simple table template to be used by simple table editor pages.
 * The html code output is not very sophisticated but can be used as a starting point
 * for a pagelayout to implement a simple table editor. The data in the template is
 * derived from the column-names of the relation selected in the selct-box.  
 */
require_once("peerutils.php");
require_once("utils.php");
require_once('navigation2.php');
//require_once("nav6.php");
//requireCap(CAP_SYSTEM);
//if ($am_user_blocked == 'J') {
//  include("blocked_tail.inc");
//  exit;
//}
$page_opening= "Peerweb genereer simpele forms voor DB-relaties";
if (isSet($_GET['table_name'])) {
	$table_name=trim($_GET['table_name']);
} else {
  $table_name='';
}
if (isSet($_GET['veld_naam'])) {
	$veld_naam=trim($_GET['veld_naam']);
} else {
  $veld_naam='veld';
}
$sql ="SELECT table_name as name, table_name as value from information_schema.tables WHERE table_schema = 'public'";
pagehead('Form generator');
$nav=new Navigation($tutor_navtable, basename($PHP_SELF), $page_opening);
$nav->setInterestMap($tabInterestCount);
$nav->show();

?>
<div id='navmain' style='padding:1em;'>
<?php
echo 'Het include path ='.ini_get('include_path');
$arr=array();
global $PHP_SELF;
$sql2="select distinct table_name as name, table_name as value from information_schema.columns where table_schema='public' order by name";
?>
<h2>Form genereren</h2>
<p>Hiermee kun je een eenvoudige tabel voor in een 'form' laten genereren voor een database relatie (table of view).</p>
<p>Deze versie is nog niet erg slim. Met name bij het gebruik van de gegenereerd tabel uit een view moet je verstandig
omgaan met de primary key velden van de (onderliggende database-)tabel. </p>
Dat kan door de betreffende bijvoorbeeld als niet muteerbare invoervelden te definieren.<br/>
<form name="gettable" method="GET" action="<?=$PHP_SELF?>">
<table>
<tr>
<td>Tabel of view</td>
<td>prefix</td><td>&nbsp;</td>
</tr>
<tr>
<td>
<select name="table_name">
  <?php echo getOptionList($dbConn,$sql2,$table_name); ?>
</select>
</td>
<td><input type="text" name="veld_naam" value="veld"></td>
<td><input class="button" type="submit" name="submit" value="Genereer"></td>
</tr>
</table>
</form>
<hr>
<?php
if ($table_name != '') {
  $result='<fieldset>
<legend>Menu</legend>
<table>';
  $sql ="select column_name from information_schema.columns where table_name='$table_name' order by ordinal_position";
  $resultSet= $dbConn->Execute($sql);
  while(! $resultSet->EOF) {
      extract($resultSet->fields);
      $seperator='';
      $nicename=ucfirst(strtolower($column_name));
      $nicename=str_replace('_',' ',$nicename);
      $resultSet->MoveNext();
      $result .='
<tr>
	<td>'.$nicename.'</td>
	<td><?=$'.$veld_naam.'_'.$column_name.'?></td>
</tr>
  ';
  }
  $result .='
</table></fieldset>';
  echo "<div style=\"background-color:white;\"><pre>";
  highlight_string($result);
  echo '&lt;!-- autogenerated by genform.php on '.date('Y-m-d H:i ').' --&gt;';
  echo '</pre></div>';

}	
?>
<?php
  //navEnd('Einde van '.basename(__FILE__));
?>
</div>
</body>
<!-- $Id: genform.php 1723 2014-01-03 08:34:59Z hom $ -->
</html>
