<?php

$tabInterestCount = array();
$tabInterestCount['all'] = 1;
$tabInterestCount['tutor'] = hasCap(CAP_TUTOR) ? 1 : 0;
$tabInterestCount['tutor_owner'] = hasCap(CAP_TUTOR_OWNER) ? 1 : 0;
$tabInterestCount['student'] = 0;
if (!hasCap(CAP_TUTOR) || hasCap(CAP_IMPERSONATE_STUDENT)) {
    $tabInterestCount['student'] = 1;
}
$tabInterestCount['mkproject'] = hasCap(CAP_MKPROJECT) ? 1 : 0;
$tabInterestCount['adminstudent_class'] = hasCap(CAP_MKCLASSES) ? 1 : 0;
$tabInterestCount['lookupstudent'] = hasCap(CAP_LOOKUP_STUDENT) ? 1 : 0;
$tabInterestCount['hunter'] = hasCap(CAP_JAAG) ? 1 : 0;
$tabInterestCount['recruiter'] = hasCap(CAP_RECRUITER) ? 1 : 0;
$tabInterestCount['system'] = hasCap(CAP_SYSTEM) ? 1 : 0;
$tabInterestCount['menu_admin'] = hasCap(CAP_MENU_ADMIN) ? 1 : 0;
$tabInterestCount['subversion'] = hasCap(CAP_SUBVERSION) ? 1 : 0;
$tabInterestCount['student_admin'] = hasCap(CAP_STUDENT_ADMIN) ? 1 : 0;
$tabInterestCount['tutor_admin'] = hasCap(CAP_TUTOR_ADMIN) ? 1 : 0;
$tabInterestCount['set_capabilities'] = hasCap(CAP_EDIT_RIGHTS) ? 1 : 0;
$tabInterestCount['bigface'] = hasCap(CAP_BIGFACE) ? 1 : 0;
$tabInterestCount['module'] = hasCap(CAP_MODULES) ? 1 : 0;
$tabInterestCount['enrol'] = hasCap(CAP_ENROL) ? 1 : 0;
$tabInterestCount['git'] = hasCap(CAP_GIT) ? 1 : 0;
$tabInterestCount['sync'] = hasCap(CAP_SYNC_PROGRESS) ? 1 : 0;
$tabInterestCount['none'] = 0;
$sql = "select opl from student where snummer=$peer_id";
$resultSet = $dbConn->Execute($sql);
if ($resultSet === false) {
    die('Error: ' . $dbConn->ErrorMsg() . ' with ' . $sql);
}
$tabInterestCount['sharing'] = hasCap(CAP_SHARING);
$tabInterestCount['sharing_tutor'] = $tabInterestCount['tutor'] && $tabInterestCount['sharing'];
$tabInterestCount['act_participant'] = ($resultSet->fields['opl'] == 112);
$opl = $resultSet->fields['opl'];
$snummer = $_SESSION['snummer'];
$sql = "select count(*) as scribe_count from all_project_scribe where scribe=$peer_id";
$resultSet = $dbConn->Execute($sql);
if ($resultSet === false) {
    die('Error: ' . $dbConn->ErrorMsg() . ' with ' . $sql);
}
$tabInterestCount['project_scribe'] = ( $resultSet->fields['scribe_count'] > 0 || hasCap(CAP_TUTOR));

$tabInterestCount['deliverable_count'] = 1; //$resultSet->fields['nav_deliverable_count'];

$tabInterestCount['assessment_count'] = 1; //$resultSet->fields['assessment_count'];
$tabInterestCount['project_count'] = 1; //$resultSet->fields['project_count'];
$tabInterestCount['read_result'] = 1; //($resultSet->EOF)?0:1;
$navtable = array(// index, defproject, citeria1,2, milestones
    array(
        'interest' => 'tutor',
        'toplinktext' => 'Start page/home and class lists',
        'tooltip' => 'Here you find a home page, class/student photos and class lists',
        'menu_name' => 'tuthome',
        'image' => 'home.png',
        'subitems' =>
        array(// tutor home
            array('target' => 'tutorhome.php',
                'tooltip' => 'Home page for tutors',
                'menu_name' => 'tuthome',
                'linktext' => 'Tutor Home',
                'image' => 'home.png',
                'interest' => 'all',
            ),
            array('target' => 'classphoto.php',
                'tooltip' => 'Class photos',
                'linktext' => 'Class Photos',
                'menu_name' => 'classphoto',
                'image' => 'kontact_contacts.png',
                'interest' => 'all',
            ),
            array('target' => 'classlist.php',
                'tooltip' => 'Class lists',
                'linktext' => 'Class lists',
                'menu_name' => 'classlist',
                'image' => 'public.png',
                'interest' => 'all',
            ),
            array('target' => 'hoofdgrplist.php',
                'tooltip' => 'List by Hoofdgrp',
                'linktext' => 'alt: Hoofdgrp ',
                'menu_name' => 'hoofdgrplist',
                'image' => 'public.png',
                'interest' => 'adminstudent_class',
            ),
            array('target' => 'slblist.php',
                'tooltip' => 'List by slb',
                'linktext' => 'slb pupils',
                'menu_name' => 'slblist',
                'image' => 'public.png',
                'interest' => 'adminstudent_class',
            ),
//		     array( 'target'=> 'buit.php',
//			    'tooltip' => 'Formulier jaag actie',
//			    'linktext' => 'Jaag scherm',
//			    'menu_name' =>'buit',
//			    'image'=> 'bowandarrow.png',
//			    'interest' =>'hunter',
//			    ),
//		     array( 'target'=> 'jaag_buit.php',
//			    'tooltip' => 'Resultaat jaag actie',
//			    'linktext' => 'Jaag resultaat',
//			    'menu_name' =>'jaagbuit',
//			    'image'=> 'Boogschutter_thumb.png',
//			    'interest' =>'hunter',
//			    ),
        ), // tutor home
    ),
    array(
        'interest' => 'tutor_owner',
        'toplinktext' => 'Project base data',
        'tooltip' => 'Define top level attributes of a project, like project name, dates and owner',
        'menu_name' => 'project',
        'image' => 'wip-icon.png',
        'subitems' =>
        array(// define project
            array('target' => 'defproject.php',
                'tooltip' => 'Enter the project data',
                'linktext' => '(1) Define a new project',
                'menu_name' => 'defproj',
                'image' => 'blank.png',
                'interest' => 'mkproject',
            ),
            array('target' => 'alterproject.php',
                'tooltip' => 'Update the project data',
                'linktext' => '(?) Alter a project',
                'menu_name' => 'altprj',
                'image' => 'alter_project.png',
                'interest' => 'mkproject',
            ),
            array('target' => 'addmilestone.php',
                'tooltip' => 'Add another assessment milestone',
                'linktext' => 'Add/change milestone(s)',
                'menu_name' => 'addmilestone',
                'image' => 'milestone1.png',
                'interest' => 'tutor_owner',
            ),
            array('target' => 'addscribe.php',
                'tooltip' => 'add a project scribe/assistant.',
                'linktext' => 'Add a project scribe',
                'menu_name' => 'addscribe',
                'image' => 'scribe.png',
                'interest' => 'tutor_owner',
            ),
        ),
    ),
    array(// define group
        'interest' => 'tutor_owner',
        'toplinktext' => 'Project Group definitions',
        'tooltip' => 'Here you define group related things',
        'menu_name' => 'altgroupsize',
        'image' => 'view_icon.png',
        'subitems' =>
        array(// define groups
            array('target' => 'copygroups.php',
                'tooltip' => 'Copy project groups',
                'linktext' => '(?) Copy groups',
                'menu_name' => 'copygroups',
                'image' => 'view_sidetree.png',
                'interest' => 'mkproject',
            ),
            array('target' => 'defgroupsize.php',
                'tooltip' => 'Select group count and assign tutor',
                'linktext' => '(1) Set #groups/tutors',
                'menu_name' => 'altgroupsize',
                'image' => 'view_icon.png',
                'interest' => 'mkproject',
            ),
            array('target' => 'defgroup.php',
                'tooltip' => 'Choose the student_class of participating students.',
                'linktext' => '(2) Choose class(es)',
                'menu_name' => 'defgroup',
                'image' => 'filter.png',
                'interest' => 'mkproject',
            ),
            array('target' => 'addindividual.php',
                'tooltip' => 'Add individual student',
                'linktext' => '(? 3) Add individual',
                'menu_name' => 'addindividual',
                'image' => 'add_user.png',
                'interest' => 'all',
            ),
            array('target' => 'defgroupmembers2.php',
                'tooltip' => 'Distribute students in project groups',
                'linktext' => '(4) Assign groups',
                'menu_name' => 'defgroupmembers',
                'image' => 'view_sidetree.png',
                'interest' => 'mkproject',
            ),
            array('target' => 'defgroupmembersalt.php',
                'tooltip' => 'Distribute students in project groups,alternate UI',
                'linktext' => 'or (4) Alt Assign groups',
                'menu_name' => 'defgroupmembersalt',
                'image' => 'view_sidetree.png',
                'interest' => 'mkproject',
            ),
            array('target' => 'defprojectroles.php',
                'tooltip' => 'Define student roles in projects.',
                'linktext' => '(? 5) Project roles',
                'menu_name' => 'defprojectroles',
                'image' => 'source_ruby.png',
                'interest' => 'tutor',
            ),
            array('target' => 'defcontacts.php',
                'tooltip' => 'Define project contact student/person.',
                'linktext' => '(? 6) Project contacts',
                'menu_name' => 'defcontacts',
                'image' => 'kontact_contacts.png',
                'interest' => 'tutor',
            ),
            array('target' => 'createmaillists.php',
                'tooltip' => 'View and create project email lists.',
                'linktext' => '(? 7) Create Email lists',
                'menu_name' => 'createmaillists',
                'image' => 'mail_address.png',
                'interest' => 'tutor',
            ),
            array('target' => 'grpdetails.php',
                'tooltip' => 'Group attributes such as links and alt names.',
                'linktext' => '(? 8) Group details',
                'menu_name' => 'grpdetails',
                'image' => 'mail_address.png',
                'interest' => 'tutor',
            ),
            array('target' => 'importgroups.php',
                'tooltip' => 'Import group definitions from (excel)file.',
                'linktext' => 'Import Group membership',
                'menu_name' => 'importgroups',
                'image' => 'filter.png',
                'interest' => 'system',
            ),
        ),
    ),
    array(
        'interest' => 'project_scribe',
        'toplinktext' => 'Project Group Views',
        'tooltip' => 'Various ways to look at groups',
        'menu_name' => 'groupviews',
        'image' => 'binocular-icon.png',
        'subitems' =>
        array(// group views
            array('target' => 'grouplist.php',
                'tooltip' => 'Get the a list of the group',
                'linktext' => 'Group list',
                'menu_name' => 'grouplist',
                'image' => 'html2.png',
                'interest' => 'all',
            ),
            array('target' => 'groupphoto.php',
                'tooltip' => 'Group photos',
                'linktext' => ' Group Photos',
                'menu_name' => 'grouplist',
                'image' => 'kontact_contacts.png',
                'interest' => 'all',
            ),
            array('target' => 'grpdetails.php',
                'tooltip' => 'Group details',
                'linktext' => ' Group details',
                'menu_name' => 'grpdetails',
                'image' => 'kontact_contacts.png',
                'interest' => 'all',
            ),
            array('target' => 'examlist.php',
                'tooltip' => 'Candidates for a exam.',
                'linktext' => 'Exam list',
                'menu_name' => 'examlist',
                'image' => 'html2.png',
                'interest' => 'tutor_owner',
            ),
            array('target' => 'limelist.php',
                'tooltip' => 'Lime survey token table.',
                'linktext' => 'Limesurvey tokens',
                'menu_name' => 'limelist',
                'image' => 'limesurvey.png',
                'interest' => 'tutor_owner',
            ),
            array('target' => 'groupemail.php',
                'tooltip' => 'Send mail to students groups',
                'top_image' => 'mail_generic.png',
                'linktext' => 'group eMail',
                'menu_name' => 'groupemail',
                'image' => 'mail_send.png',
                'interest' => 'project_count',
            ),
        ),
    ),
    array(
        'interest' => 'tutor',
        'toplinktext' => 'Assessment setup and results',
        'tooltip' => 'Here you define the assessments and find the group results',
        'menu_name' => 'groupresult',
        'image' => 'editcut.png',
        'subitems' =>
        array(// examine results
            array('target' => 'criteria3.php',
                'tooltip' => 'Choose the criteria in the assessments in this project',
                'linktext' => 'select the criteria',
                'menu_name' => 'crit1',
                'image' => 'apply.png',
                'interest' => 'tutor_owner',
            ),
            array('target' => 'openclose.php',
                'tooltip' => 'Open or close an assessment',
                'linktext' => 'Open or close assessment',
                'menu_name' => 'openclose',
                'image' => 'lock-unlock.png',
                'interest' => 'tutor_owner',
            ),
            array('target' => 'groupresult.php',
                'tooltip' => 'Get the results for a projectgroup.',
                'linktext' => 'Group result',
                'menu_name' => 'groupresult',
                'image' => 'editcut.png',
                'interest' => 'tutor',
            ),
            array('target' => 'allgroupresults.php',
                'tooltip' => 'Get the results for all groups.',
                'linktext' => 'All Group result',
                'menu_name' => 'allgroupresults',
                'image' => 'editcut.png',
                'interest' => 'tutor',
            ),
            array('target' => 'dueassessment.php',
                'tooltip' => 'Here you see the students with over due peer assessments',
                'linktext' => 'overdue assessment',
                'menu_name' => 'dueassessments',
                'image' => 'ktip.png',
                'interest' => 'tutor',
            ),
            array('target' => 'moduleresults.php',
                'tooltip' => 'Get the unprocessed scores of entered by the participating judges.',
                'linktext' => 'Score data',
                'menu_name' => 'scoredata',
                'image' => 'define_clip.png',
                'interest' => 'tutor',
            ),
            array('target' => 'addmilestone.php',
                'tooltip' => 'Add another assessment milestone',
                'linktext' => 'Add/change milestone(s)',
                'menu_name' => 'addmilestone',
                'image' => 'milestone1.png',
                'interest' => 'tutor_owner',
            ),
            array('target' => 'milestonegrades.php',
                'tooltip' => 'View results of project milestones and totals',
                'linktext' => 'Overall project results',
                'menu_name' => 'milestonegrades',
                'image' => 'milestonegrades.png',
                'interest' => 'tutor',
            ),
            array('target' => 'project_attributes_def.php',
                'tooltip' => 'Define project attributes or performance indicators',
                'linktext' => 'Project attributes',
                'menu_name' => 'projectattributesdef',
                'image' => 'milestonegrades.png',
                'interest' => 'tutor_owner',
            ),
        ),
    ),
    array(
        'interest' => 'sharing_tutor',
        'toplinktext' => 'Uploads, portfolios and repositories',
        'tooltip' => 'Here you define and view student uploads',
        'menu_name' => 'defuploadtype',
        'image' => 'filesaveas.png',
        'subitems' =>
        array(// files etc
            array('target' => 'defuploadtype.php',
                'tooltip' => 'Define the documents to upload.',
                'linktext' => 'eDeliverables',
                'menu_name' => 'defuploadtype',
                'image' => 'folder_inbox.png',
                'interest' => 'tutor',
            ),
            array('target' => 'groupuploads.php',
                'tooltip' => 'View uploads per project and doc type.',
                'linktext' => 'View uploads per doctype',
                'menu_name' => 'groupuploads',
                'image' => 'filefind.png',
                'interest' => 'tutor',
            ),
            array('target' => 'groupuploadsall.php',
                'tooltip' => 'View all uploads per project.',
                'linktext' => 'View all uploads per project+milestone',
                'menu_name' => 'groupuploadsall',
                'image' => 'filefind.png',
                'interest' => 'tutor',
            ),
            array('target' => 'subversionrepos.php',
                'tooltip' => 'Create svn repositories for a project.',
                'linktext' => 'svn repositories',
                'menu_name' => 'examlist',
                'image' => 'subversion.png',
                'interest' => 'subversion',
            ),
        ),
    ),
    array(
        'interest' => 'tutor_owner',
        'toplinktext' => 'Activity presence registration',
        'tooltip' => 'Activities like excursions and colloquia',
        'menu_name' => 'collo',
        'image' => 'dilbert_icon.png',
        'subitems' =>
        array(
            array('target' => 'defactivity.php',
                'tooltip' => 'Define activity.',
                'linktext' => 'Define Activity',
                'menu_name' => 'defactivity',
                'image' => 'blank.png',
                'interest' => 'tutor_owner',
            ),
            array('target' => 'deftask.php',
                'tooltip' => 'define task to project.',
                'linktext' => 'Define tasks.',
                'menu_name' => 'deftask',
                'image' => 'checkmark.png',
                'interest' => 'tutor_owner',
            ),
            array('target' => 'addscribe.php',
                'tooltip' => 'add a project scribe.',
                'linktext' => 'Add a project scribe',
                'menu_name' => 'addscribe',
                'image' => 'scribe.png',
                'interest' => 'tutor_owner',
            ),
            array('target' => 'presencelist.php',
                'tooltip' => 'Presence to activities.',
                'linktext' => 'Presence to activities.',
                'menu_name' => 'presencelist',
                'image' => 'html2.png',
                'interest' => 'all',
            ),
            array('target' => 'presenceoverview.php',
                'tooltip' => 'Overview of Presence to activities.',
                'linktext' => 'Overview of Presence to activities.',
                'menu_name' => 'presenceOverview ',
                'image' => 'public.png',
                'interest' => 'all',
            ),
        ),
    ),
    array(
        'interest' => 'project_scribe',
        'toplinktext' => 'Register presence and tasks',
        'tooltip' => 'Record task completion for tutors',
        'menu_name' => 'project_scribe',
        'image' => 'takenote.png',
        'subitems' =>
        array(// scribe views
            array('target' => 'defactivity.php',
                'tooltip' => 'Define activity.',
                'linktext' => 'Define Activity',
                'menu_name' => 'defactivity',
                'image' => 'blank.png',
                'interest' => 'project_scribe',
            ),
            array('target' => 'deftask.php',
                'tooltip' => 'define task to project.',
                'linktext' => 'Define tasks.',
                'menu_name' => 'deftask',
                'image' => 'checkmark.png',
                'interest' => 'project_scribe',
            ),
            array('target' => 'presencelist.php',
                'tooltip' => 'Presence to activities.',
                'linktext' => 'Presence to activities.',
                'menu_name' => 'presencelist',
                'image' => 'html2.png',
                'interest' => 'project_scribe',
            ),
            array('target' => 'presenceoverview.php',
                'tooltip' => 'Overview of Presence to activities.',
                'linktext' => 'Overview of Presence to activities.',
                'menu_name' => 'presenceOverview ',
                'image' => 'public.png',
                'interest' => 'project_scribe',
            ),
            array('target' => 'tasklist.php',
                'tooltip' => 'Task recording.',
                'linktext' => 'Record and grade completed tasks',
                'menu_name' => 'tasklist',
                'image' => 'takenote.png',
                'interest' => 'project_scribe',
            ),
            array('target' => 'taskoverview.php',
                'tooltip' => 'Tasks completed.',
                'linktext' => 'Tasks completed.',
                'menu_name' => 'taskOverview ',
                'image' => 'checkmarks.png',
                'interest' => 'project_scribe',
            ),
        ),
    ),
    array(
        'interest' => 'recruiter',
        'toplinktext' => 'Recruiter peer pages',
        'tooltip' => 'Recruiters sharing information',
        'menu_name' => 'recruitertop',
        'image' => 'womanincape.png',
        'subitems' =>
        array(
            array('target' => 'planned_school_visit.php',
                'tooltip' => 'School visit by recruiters',
                'linktext' => 'Plan and share a school visit',
                'menu_name' => 'planned_school_visit',
                'image' => 'calendar.png',
                'interest' => 'recruiter',
            ),
            array('target' => 'schulen.php',
                'tooltip' => 'Schulen NRW.',
                'linktext' => 'Schulen Editor',
                'menu_name' => 'schulen',
                'image' => 'file_cabinet.png',
                'interest' => 'recruiter',
            ),
            array('target' => 'scholen_int.php',
                'tooltip' => 'Scholen NL/int.',
                'linktext' => 'Scholen Editor',
                'menu_name' => 'scholen_int',
                'image' => 'file_cabinet.png',
                'interest' => 'recruiter',
            ),
            array('target' => 'verbaende.php',
                'tooltip' => 'Verbände Deutschland.',
                'linktext' => 'Verbände Editor',
                'menu_name' => 'verbände',
                'image' => 'file_cabinet.png',
                'interest' => 'recruiter',
            ),
            array('target' => 'presse.php',
                'tooltip' => 'Press contacts.',
                'linktext' => 'Press Editor',
                'menu_name' => 'presscontacts',
                'image' => 'file_cabinet.png',
                'interest' => 'recruiter',
            ),
            array('target' => 'meelopen.php',
                'tooltip' => 'Meelopen student',
                'linktext' => 'Meelopen student',
                'menu_name' => 'meelopen',
                'image' => 'shaking_hands_icn.png',
                'interest' => 'recruiter',
            ),
            array('target' => 'meeloopdag.php',
                'tooltip' => 'Plan meeloopdag',
                'linktext' => 'Plan meeloopdag',
                'menu_name' => 'meeloopdag',
                'image' => 'plan_invite.png',
                'interest' => 'recruiter',
            ),
        ),
    ),
    array(
        'interest' => 'module',
        'toplinktext' => 'Module pages',
        'tooltip' => 'Module administration',
        'menu_name' => 'module',
        'image' => 'lego-tiny.png',
        'subitems' =>
        array(
            array('target' => 'module.php',
                'tooltip' => 'Module ',
                'linktext' => 'Module',
                'menu_name' => 'mod',
                'image' => 'lego-tiny.png',
                'interest' => 'module',
            ),
            array('target' => 'module_part.php',
                'tooltip' => 'Module part',
                'linktext' => 'Module part',
                'menu_name' => 'mod_part',
                'image' => 'lego-tiny.png',
                'interest' => 'module',
            ),
            array('target' => 'module_activity_description.php',
                'tooltip' => 'Module details',
                'linktext' => 'Module activity',
                'menu_name' => 'mod_activity',
                'image' => 'lego-tiny.png',
                'interest' => 'module',
            ),
            array('target' => 'exam_event.php',
                'tooltip' => 'Define exam event',
                'linktext' => 'Exam Event',
                'menu_name' => 'exam_event',
                'image' => 'lego-tiny.png',
                'interest' => 'module',
            ),
            array('target' => 'uploadGrades.php',
                'tooltip' => 'Upload exam grades',
                'linktext' => 'Upload Grades',
                'menu_name' => 'upload_grades',
                'image' => 'file_cabinet.png',
                'interest' => 'module',
            ),
            array('target' => 'examresults.php',
                'tooltip' => 'View exam grades',
                'linktext' => 'View Grades',
                'menu_name' => 'viewUpload_grades',
                'image' => 'file_cabinet.png',
                'interest' => 'module',
            ),
        ),
    ),
    array(
        'interest' => 'enrol',
        'toplinktext' => 'Enrol  students',
        'tooltip' => 'Enrolment',
        'menu_name' => 'enroll',
        'image' => 'new-22a.png',
        'subitems' =>
        array(
            array('target' => 'importfromprogress.php',
                'tooltip' => 'Import students from progress',
                'linktext' => 'import students',
                'menu_name' => 'importstudents',
                'image' => 'filter.png',
                'interest' => 'enrol',
            ),
            array('target' => 'enrol_prospect.php',
                'tooltip' => 'Enrol student into peerweb ',
                'linktext' => 'enrol',
                'menu_name' => 'enrol',
                'image' => 'new-22a.png',
                'interest' => 'enrol',
            ),
            array('target' => 'prospect_admin.php',
                'tooltip' => 'Add or edit prospect data.',
                'linktext' => 'Enrol Student admin',
                'menu_name' => 'prospect_admin',
                'image' => 'file_cabinet.png',
                'interest' => 'enrol',
            ),
            array('target' => 'syncfromprogress.php',
                'tooltip' => 'sync students with progress',
                'linktext' => 'sync students data',
                'menu_name' => 'syncstudents',
                'image' => 'synchronize.png',
                'interest' => 'sync',
            ),
        ),
    ),
    array(
        'interest' => 'student_admin',
        'toplinktext' => 'Admin pages',
        'tooltip' => 'Database administration',
        'menu_name' => 'studentadmin',
        'image' => 'ooffice-extension.png',
        'subitems' =>
        array(// various admin
            array('target' => 'student_admin.php',
                'tooltip' => 'Add or edit student data.',
                'linktext' => 'Student admin',
                'menu_name' => 'studentadmin',
                'image' => 'file_cabinet.png',
                'interest' => 'lookupstudent',
            ),
            array('target' => 'classmaker.php',
                'tooltip' => 'Update classlists. Move students into student_class.',
                'linktext' => 'Update student_class',
                'menu_name' => 'classmaker',
                'image' => 'SchoolClass.png',
                'interest' => 'adminstudent_class',
            ),
            array('target' => 'classmakerbyhoofdgrp.php',
                'tooltip' => 'Update classlists. Move students into student_class.',
                'linktext' => 'Hoofdgrp to student_class',
                'menu_name' => 'classmakerbyhoofdgrp',
                'image' => 'SchoolClass.png',
                'interest' => 'adminstudent_class',
            ),
            array('target' => 'defstudent_class.php',
                'tooltip' => 'Update student_class. Add and change class definitions.',
                'linktext' => 'Class definition',
                'menu_name' => 'defstudent_class',
                'image' => 'class4b_icon.png',
                'interest' => 'adminstudent_class',
            ),
            array('target' => 'addtoclass.php',
                'tooltip' => 'Move a student by number or name to a class.',
                'linktext' => 'Move to Class',
                'menu_name' => 'addtoclass',
                'image' => 'toclass.png',
                'interest' => 'adminstudent_class',
            ),
            array('target' => 'class_cluster.php',
                'tooltip' => 'Define class groups or clusters.',
                'linktext' => 'Class clusters',
                'menu_name' => 'class_cluster',
                'image' => 'class4b_icon.png',
                'interest' => 'adminstudent_class',
            ),
            array('target' => 'slb.php',
                'tooltip' => 'Update slb assignment.',
                'linktext' => 'Set SLB',
                'menu_name' => 'slb',
                'image' => 'slb.png',
                'interest' => 'adminstudent_class',
            ),
//		     array( 'target'=> 'buit.php',
//			    'tooltip' => 'Formulier jaag actie',
//			    'linktext' => 'Jaag scherm',
//			    'menu_name' =>'buit',
//			    'image'=> 'bowandarrow.png',
//			    'interest' =>'adminstudent_class',
//			    ),
//		     array( 'target'=> 'jaag_buit.php',
//			    'tooltip' => 'Resultaat jaag actie',
//			    'linktext' => 'Jaag resultaat',
//			    'menu_name' =>'jaagbuit',
//			    'image'=> 'Boogschutter_thumb.png',
//			    'interest' =>'adminstudent_class',
//			    ),
            array('target' => 'ads_data.php',
                'tooltip' => 'Get student ads account data',
                'linktext' => 'Get ADS Account data',
                'menu_name' => 'ADS',
                'image' => 'winlogo1.png',
                'interest' => 'adminstudent_class',
            ),
            array('target' => 'base_criteria.php',
                'tooltip' => 'Declare the text and meaning of the assessment criteria',
                'linktext' => 'Declare criteria',
                'menu_name' => 'defcrit',
                'image' => 'klipper.png',
                'interest' => 'mkproject',
            ),
            array('target' => 'meelopen.php',
                'tooltip' => 'Meelopen student',
                'linktext' => 'Meelopen student',
                'menu_name' => 'meelopen',
                'image' => 'shaking_hands_icn.png',
                'interest' => 'recruiter',
            ),
            array('target' => 'meeloopdag.php',
                'tooltip' => 'Plan meeloopdag',
                'linktext' => 'Plan meeloopdag',
                'menu_name' => 'meeloopdag',
                'image' => 'plan_invite.png',
                'interest' => 'recruiter',
            ),
            array('target' => 'potential.php',
                'tooltip' => 'Potential student',
                'linktext' => 'Potential student',
                'menu_name' => 'potential',
                'image' => 'kontact_contacts.png',
                'interest' => 'recruiter',
            ),
            array('target' => 'anyselect.php',
                'tooltip' => 'Get database data with any select',
                'linktext' => 'Any select',
                'menu_name' => 'anyselct',
                'image' => 'kontact_contacts.png',
                'interest' => 'system',
            ),
            array('target' => 'projectauditor.php',
                'tooltip' => 'Manage project auditors.',
                'linktext' => 'Project auditor',
                'menu_name' => 'projectauditor',
                'image' => 'add_user.png',
                'interest' => 'adminstudent_class',
            ),
            array('target' => 'tutor.php',
                'tooltip' => 'Set data on a tutor.',
                'linktext' => 'Tutor editor',
                'menu_name' => 'tutoreditor',
                'image' => 'tutor_icon.png',
                'interest' => 'adminstudent_class',
            ),
            array('target' => 'rubberreports.php',
                'tooltip' => 'Rubber Reports.',
                'linktext' => 'Rubber Reports',
                'menu_name' => 'Rubber',
                'image' => 'Rubber_small.png',
                'interest' => 'system',
            ),
            array('target' => 'naw.php',
                'tooltip' => 'Update Name,address data',
                'linktext' => 'NA data',
                'menu_name' => 'naw',
                'image' => 'cervisia.png',
                'interest' => 'adminstudent_class',
            ),
            array('target' => 'known_courses2.php',
                'tooltip' => 'List of known courses.',
                'linktext' => 'Known courses',
                'menu_name' => 'knowncourses',
                'image' => 'cervisia.png',
                'interest' => 'adminstudent_class',
            ),
            array('target' => 'editcapabilities.php',
                'tooltip' => 'Set User capabilities',
                'linktext' => 'User capabilities',
                'menu_name' => 'capabilities',
                'image' => 'badge_mini.png',
                'interest' => 'set_capabilities',
            ),
            array('target' => 'tutorcluster.php',
                'tooltip' => 'Set tutor class cluster(s)',
                'linktext' => 'Tutor class groups',
                'menu_name' => 'tutorcluster',
                'image' => 'wrench_driver.png',
                'interest' => 'set_capabilities',
            ),
            array('target' => 'peer_settings.php',
                'tooltip' => 'Peerweb settings',
                'linktext' => 'Peerweb settings',
                'menu_name' => 'Peerweb settings',
                'image' => 'wrench_driver.png',
                'interest' => 'system',
            ),
            array('target' => 'iso3166.php',
                'tooltip' => 'Country table',
                'linktext' => 'Country table',
                'menu_name' => 'Country table',
                'image' => 'wrench_driver.png',
                'interest' => 'system',
            ),
            array('target' => 'nat_mapper.php',
                'tooltip' => 'Translate nat to country code',
                'linktext' => 'nat mapper',
                'menu_name' => 'nat mapper',
                'image' => 'wrench_driver.png',
                'interest' => 'system',
            ),
        ),
    ),
    array(
        'interest' => 'menu_admin',
        'toplinktext' => 'Menu Table management',
        'tooltip' => 'Database administration for the gui menus',
        'menu_name' => 'menuphp',
        'image' => 'cervisia.png',
        'subitems' =>
        array(// table management
            array('target' => 'menu.php',
                'tooltip' => 'Table management.',
                'linktext' => 'Update menu',
                'menu_name' => 'menuphp',
                'image' => 'cervisia.png',
                'interest' => 'menu_admin',
            ),
            array('target' => 'menu_items.php',
                'tooltip' => 'Menu Items.',
                'linktext' => 'Update menu_item',
                'menu_name' => 'menuitems',
                'image' => 'cervisia.png',
                'interest' => 'menu_admin',
            ),
            array('target' => 'menu_option_queries.php',
                'tooltip' => 'Menus select options.',
                'linktext' => 'Update menu_option_queries',
                'menu_name' => 'menuoptionqueries',
                'image' => 'cervisia.png',
                'interest' => 'menu_admin',
            ),
            array('target' => 'enumeraties.php',
                'tooltip' => 'Edit menu enumerations',
                'linktext' => 'Enumerations',
                'menu_name' => 'enumeraties',
                'image' => 'cervisia.png',
                'interest' => 'menu_admin',
            ),
            array('target' => 'genform.php',
                'tooltip' => 'Generate simple menu form.',
                'linktext' => 'Generate Form',
                'menu_name' => 'formgenerator',
                'image' => 'design.png',
                'interest' => 'menu_admin',
            ),
            array('target' => 'regextester.php',
                'tooltip' => 'Test regexes.',
                'linktext' => 'Rgex tester',
                'menu_name' => 'regextester',
                'image' => 'configure.png',
                'interest' => 'menu_admin',
            ),
            array('target' => 'validator_regex.php',
                'tooltip' => 'Edit regexes.',
                'linktext' => 'Regex Editor',
                'menu_name' => 'validator regex editor',
                'image' => 'configure.png',
                'interest' => 'menu_admin',
            ),
            array('target' => 'validator_map.php',
                'tooltip' => 'Connect regexes to input fields.',
                'linktext' => 'Regex Mapper',
                'menu_name' => 'validator map editor',
                'image' => 'configure.png',
                'interest' => 'menu_admin',
            ),
        ),
    ),
    array(
        'interest' => 'student',
        'toplinktext' => 'My peerweb',
        'tooltip' => 'The student peerweb pages, home',
        'menu_name' => 'home',
        'image' => 'home.png',
        'subitems' =>
        array(// student start
            array('target' => 'home.php',
                'tooltip' => 'Welcome to peerweb',
                'linktext' => 'Home',
                'menu_name' => 'home',
                'image' => 'home.png',
                'interest' => 'all',
            ),
            array('target' => 'activeprojects.php',
                'tooltip' => 'Active project groups',
                'linktext' => 'Active projects',
                'menu_name' => 'activepojects',
                'image' => 'folder_image.png',
                'interest' => 'all',
            ),
            array('target' => 'activegroup.php',
                'tooltip' => 'Active group settings',
                'linktext' => 'Active group',
                'menu_name' => 'activegroup',
                'image' => 'group_files.png',
                'interest' => 'all',
            ),
            array('target' => 'visited_colloquia.php',
                'tooltip' => 'Activities you attended',
                'linktext' => 'Activities visited',
                'menu_name' => 'visitedcolloquia',
                'image' => 'group_files.png',
                'interest' => 'act_participant',
            ),
            array('target' => 'peerpresenceoverview.php',
                'tooltip' => 'Your presence lists',
                'linktext' => 'Presence to activities',
                'menu_name' => 'activitiespresent',
                'image' => 'public.png',
                'interest' => 'act_participant',
            ),
            array('target' => 'peertaskoverview.php',
                'tooltip' => 'My practica task overview',
                'linktext' => 'My task status',
                'menu_name' => 'peertaskoverview',
                'image' => 'takenote.png',
                'interest' => 'act_participant',
            ),
            array('target' => 'mypeergroups.php',
                'tooltip' => 'Your group memberships',
                'linktext' => 'Memberships',
                'menu_name' => 'mypeergroups',
                'image' => 'kontact_contacts.png',
                'interest' => 'all',
            ),
            array('target' => 'myclass.php',
                'tooltip' => 'Photos of your classmates',
                'linktext' => 'Classmate photos',
                'menu_name' => 'myclass',
                'image' => 'dilbert_icon.png',
                'interest' => 'all',
            ),
        ),
    ),
    array(
        'interest' => 'student',
        'toplinktext' => 'Peer assessment',
        'tooltip' => 'The student peer assessment pages',
        'menu_name' => 'ipeer',
        'image' => 'kontact_contacts.png',
        'subitems' =>
        array(// group and assessment
            array('target' => 'igroupphoto.php',
                'tooltip' => 'Group members',
                'top_image' => 'dilbert_icon.png',
                'linktext' => 'Group photos',
                'menu_name' => 'groupphotos',
                'image' => 'dilbert_icon.png',
                'interest' => 'assessment_count',
            ),
            array('target' => 'ipeer.php',
                'tooltip' => 'Enter or update the assessment grades',
                'top_image' => 'kontact_contacts.png',
                'linktext' => 'Assessment',
                'menu_name' => 'ipeer',
                'image' => 'kontact_contacts.png',
                'interest' => 'assessment_count',
            ),
            array('target' => 'iresult.php',
                'tooltip' => 'View own assessment grades',
                'linktext' => 'Assessment Results',
                'menu_name' => 'iresult',
                'image' => 'kontact_summary.png',
                'interest' => 'assessment_count',
            ),
            array('target' => 'icontestant.php',
                'tooltip' => 'View received detail grades',
                'linktext' => 'Assessment Grades by judges',
                'menu_name' => 'icontestant',
                'image' => 'contestantResult.png',
                'interest' => 'student_admin',
            ),
            array('target' => 'mypeerresults.php',
                'tooltip' => 'Your peer results',
                'linktext' => 'All Assessments',
                'menu_name' => 'mypeerresults',
                'image' => 'kontact_contacts.png',
                'interest' => 'all',
            ),
            array('target' => 'rolesetter.php',
                'tooltip' => 'Set or view roles for peers in project group',
                'linktext' => 'Student Roles',
                'menu_name' => 'rolesetter',
                'image' => 'kontact_summary.png',
                'interest' => 'project_count',
            ),
            array('target' => 'studentgroupresult.php',
                'tooltip' => 'Read peer group assessment result',
                'linktext' => 'Group result',
                'menu_name' => 'studentgroupresult',
                'image' => 'kontact_contacts.png',
                'interest' => 'read_result',
            ),
            array('target' => 'imail.php',
                'tooltip' => 'Send mail to fellow students',
                'top_image' => 'mail_generic.png',
                'linktext' => 'group eMail',
                'menu_name' => 'imail',
                'image' => 'mail_send.png',
                'interest' => 'project_count',
            ),
            array('target' => 'emailer.php',
                'tooltip' => 'Send a mail to single recipient',
                'top_image' => 'mail_generic.png',
                'linktext' => 'Single Mail',
                'menu_name' => 'emailer',
                'image' => 'mail_send.png',
                'interest' => 'all',
            ),
        ),
    ),
    array(
        'interest' => 'sharing',
        'toplinktext' => 'My Portfolio and shared stuff',
        'tooltip' => 'The student portfolios and shared documents',
        'menu_name' => 'portfolio',
        'image' => 'group_files.png',
        'subitems' =>
        array(// sharing
            array('target' => 'portfolio.php',
                'tooltip' => 'Your Portfolio',
                'linktext' => 'Portfolio',
                'menu_name' => 'portfolio',
                'image' => 'folder_green_open.png',
                'interest' => 'deliverable_count',
            ),
            array('target' => 'upload.php',
                'tooltip' => 'Upload your documents',
                'top_image' => 'group_files.png',
                'linktext' => 'Upload',
                'menu_name' => 'upload',
                'image' => 'fileuploadicon.png',
                'interest' => 'deliverable_count',
            ),
            array('target' => 'uploadviewer.php',
                'tooltip' => 'View and critisize project files',
                'linktext' => 'Group Files',
                'menu_name' => 'uploadviewer',
                'image' => 'group_files.png',
                'interest' => 'deliverable_count',
            ),
            array('target' => 'igrouprepos.php',
                'tooltip' => 'Show my group repositories',
                'linktext' => 'Group Repositories',
                'menu_name' => 'ireposviewer',
                'image' => 'group_repos.png',
                'interest' => 'subversion',
            ),
            array('target' => 'isubversionrepos.php',
                'tooltip' => 'Manage your personal svn repositories',
                'linktext' => 'Manage personal SVN repository',
                'menu_name' => 'create a svn repository',
                'image' => 'subversion.png',
                'interest' => 'subversion',
            ),
            array('target' => 'gitkey.php',
                'tooltip' => 'Manage your personal GIT ssh keys',
                'linktext' => 'Manage personal GIT keys',
                'menu_name' => 'manage you git keys',
                'image' => 'git.png',
                'interest' => 'git',
            ),
        ),
    ),
    array(
        'interest' => 'system',
        'toplinktext' => 'Time and presence',
        'tooltip' => 'Time keeping and student presence',
        'menu_name' => 'personalpresence',
        'image' => 'group_presence.png',
        'subitems' =>
        array(// time and presence
            array(
                'target' => 'personal_presence.php',
                'tooltip' => 'presence at computer in the fontys network',
                'top_image' => 'player_time.png',
                'linktext' => 'Presence',
                'menu_name' => 'personalpresence',
                'image' => 'edu_languages.png',
                'interest' => 'project_count',
            ),
            array(
                'target' => 'group_presence.php',
                'tooltip' => 'group presence at computers in the fontys network',
                'linktext' => 'Group Presence',
                'menu_name' => 'grouppresence',
                'image' => 'group_presence.png',
                'interest' => 'project_count',
            ),
            array('target' => 'grouptime.php',
                'tooltip' => 'Time records of my group',
                'linktext' => 'Group Time',
                'menu_name' => 'grouptime',
                'image' => 'group_time.png',
                'interest' => 'project_count',
            ),
            array('target' => 'project_tasks.php',
                'tooltip' => 'Your defined tasks',
                'top_image' => 'player_time.png',
                'linktext' => 'Project tasks',
                'menu_name' => 'gprojecttasks',
                'image' => 'player_time.png',
                'interest' => 'all',
            ),
            array('target' => 'timebook.php',
                'tooltip' => 'Various personal settings',
                'top_image' => 'player_time.png',
                'linktext' => 'Time book keeping',
                'menu_name' => 'timebook',
                'image' => 'player_time.png',
                'interest' => 'all',
            ),
            array('target' => 'tasktimer.php',
                'tooltip' => 'The task timer',
                'top_image' => 'player_time.png',
                'linktext' => 'Task timer',
                'menu_name' => 'tasktimer',
                'image' => 'player_time.png',
                'interest' => 'all',
            ),
        ),
    ),
    array(
        'interest' => 'all',
        'toplinktext' => 'Personal data and settings',
        'tooltip' => 'Her you can view or modify your personal data',
        'image' => 'configure.png',
        'menu_name' => 'personaldata',
        'subitems' =>
        array(// personal data
            array('target' => 'myface.php',
                'tooltip' => 'My image on peerweb',
                'linktext' => 'my peer photo',
                'menu_name' => 'personal photo',
                'image' => 'dilbert_icon.png',
                'interest' => 'all',
            ),
            array('target' => 'emailaddress.php',
                'tooltip' => 'Personal data and email addressess',
                'linktext' => 'personal data and email addres',
                'menu_name' => 'personaldata',
                'image' => 'mail_address.png',
                'interest' => 'all',
            ),
            array('target' => 'signature.php',
                'tooltip' => 'Set the emailer signature',
                'top_image' => 'mail_generic.png',
                'linktext' => 'eMail signature',
                'menu_name' => 'emailer',
                'image' => 'signature.png',
                'interest' => 'all',
            ),
            array('target' => 'bigface_settings.php',
                'tooltip' => 'Setting voor smoelenbord fibs',
                'linktext' => 'Setting voor smoelenbord fibs',
                'menu_name' => 'personaldata',
                'image' => 'dilbert_icon.png',
                'interest' => 'bigface',
            ),
        ),
    ),
);
$tutor_navtable = $navtable;
?>
