<tr>
   <th $tdStyle>$i</th>
   <th $tdStyle>Short.</th>
   <td $tdStyle><input type='text' size='20' name='nl_short[]' value='$nl_short[$i]'/></td>
   <td $tdStyle><input type='text' size='20' name='de_short[]' value='$de_short[$i]'/></td>
   <td $tdStyle><input type='text' size='20' name='en_short[]' value='$en_short[$i]'/></td>
</tr>
<tr>
   <th $tdStyle colspan='2'>Long<br/> description</th>
   <td $tdStyle><textarea name='nl[]' cols='30' rows='5'>$nl[$i]</textarea></td>
   <td $tdStyle><textarea name='de[]' cols='30' rows='5'>$de[$i]</textarea></td>
   <td $tdStyle><textarea name='en[]' cols='30' rows='5'>$en[$i]</textarea></td>
</tr>
