<!-- \$Id: criteria2bottom.html.inc 1723 2014-01-03 08:34:59Z hom $ -->
  <tr>
    <th colspan='4' class='theadleft' style='text-align:center'>Owning tutor $tutor_owner&nbsp;: $roepnaam $voorvoegsel $achternaam</th>
    <th class='theadright'></th>
  </tr>
  <tr>
    <th colspan='3' class='theadleft'>$submit_button</th>
    <th colspan='1' class='theadmid'></th>
    <th class='theadright'>$critcount</th>
    </tr>
</table>
<!-- end template \$Id: criteria2bottom.html.inc 1723 2014-01-03 08:34:59Z hom $ -->
