<!-- criteria1.html.inc -->
<table border='3' style='empty-cells:show;border-collapse:3d' rules='groups' frame='box' summary='number of criteria form'>
  <colgroup>
    <col width='50%'/>
      <col width='50%'/>
  </colgroup>
  <thead> 
    <tr><th class='theadleft'>$prj_id $afko $description</th><th class='theadright'>$year</th></tr>
  </thead>
  <tr><th class='thl'>Project Id (for change)</th><td>$project_selector</td></tr>
  <tr><th class='thl'>Number of criteria</th><td>$input_num_criteria&nbsp;$input_submit_button</td></tr>
  <thead> 
    <tr><th class='theadleft'>Owning tutor</th><th class='theadright'>$tutor_owner:&nbsp;$roepnaam $tussenvoegsel $achternaam</th></tr>
  </thead>
</table>
<!-- end template criteria1.html.inc \$Id: criteria1.html.inc 1723 2014-01-03 08:34:59Z hom $ -->
