<!-- criteria2top.html.inc -->
<table border='3' style='empty-cells:show;border-collapse:3d' rules='groups' frame='box' summary='criteria form'>
  <colgroup>
    <col width='50%'/>
      <col width='50%'/>
  </colgroup>
    <tr>
      <th colspan='3' class='theadleft'>$prj_id $afko $description</th>
      <th colspan='3' class='theadright'>Year $year</th>
    </tr>
    <tr>
      <th colspan='2' class='theadleft'></th>
      <th colspan='2' class='theadmid'>$project_selector $get_button</th>
      <th colspan='1' class='theadright'></th>
    </tr>
    <tr>
      <th class='theadleft'>&#35;</th>
      <th class='theadmid'>Language</th>
      <th class='theadmid'>Nederlands</th>
      <th class='theadmid'>Deutsch</th>
      <th class='theadright' style='text-align:left'>English</th>
    </tr>
  <!-- end template \$Id: criteria2top.html.inc 1723 2014-01-03 08:34:59Z hom $ -->
