<!-- start \$Id: defcontacts1.html.inc 1723 2014-01-03 08:34:59Z hom $ -->
<table summary='project data'>
  <tr>
    <th colspan='2'>$prj_id $afko $description $year</th>
  </tr>
  <tr>
    <th>Project Id (for change)</th>
    <td>$prj_id_selector</td>
  </tr>
  <tr>
    <th>Owning tutor</th>
    <th>$tutor_owner:&nbsp;$roepnaam $voorvoegsel $achternaam</th>
  </tr>
</table>
<!-- end template \$Id: defcontacts1.html.inc 1723 2014-01-03 08:34:59Z hom $ -->
