<fieldset>
<legend>Exam Event</legend>
<table>
<tr>
    <td>Exam event id</td>
    <td><?=$veld_exam_event_id?></td>
</tr>
  
<tr>
    <td>Module part id</td>
    <td><?=$veld_module_part_id?></td>
</tr>
  
<tr>
    <td>Exam date</td>
    <td><?=$veld_exam_date?></td>
</tr>
  
<tr>
    <td>Examiner</td>
    <td><?=$veld_examiner?></td>
</tr>
  
</table></fieldset>
<!-- autogenerated by genform.php on 2013-11-24 18:01  -->