<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-07-26 at 11:19:38.
 */
class PeerPGDBConnectionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PeerPGDBConnection
     */
    protected $connection;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->connection = new PeerPGDBConnection;
        $this->connection->Connect("localhost", "muk" , "muk" , "mak" );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PeerPGDBConnection::Connect
     * @todo   Implement testConnect().
     */
    public function testConnect() {
        // Remove the following lines when you implement this test.
        
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::MetaType
     * @todo   Implement testMetaType().
     */
    public function testMetaType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::Execute
     * @todo   Implement testExecute().
     */
    public function testExecute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::executeQueryList
     * @todo   Implement testExecuteQueryList().
     */
    public function testExecuteQueryList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::Affected_Rows
     * @todo   Implement testAffected_Rows().
     */
    public function testAffected_Rows() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::doOrDie
     * @todo   Implement testDoOrDie().
     */
    public function testDoOrDie() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::doSilent
     * @todo   Implement testDoSilent().
     */
    public function testDoSilent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::transactionStart
     * @todo   Implement testTransactionStart().
     */
    public function testTransactionStart() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::createTransactionId
     * @todo   Implement testCreateTransactionId().
     */
    public function testCreateTransactionId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::transactionEnd
     * @todo   Implement testTransactionEnd().
     */
    public function testTransactionEnd() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::dbStackTrace
     * @todo   Implement testDbStackTrace().
     */
    public function testDbStackTrace() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::logError
     * @todo   Implement testLogError().
     */
    public function testLogError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::logContext
     * @todo   Implement testLogContext().
     */
    public function testLogContext() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::getContext
     * @todo   Implement testGetContext().
     */
    public function testGetContext() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::log
     * @todo   Implement testLog().
     */
    public function testLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::logToFile
     * @todo   Implement testLogToFile().
     */
    public function testLogToFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::getLastMsg
     * @todo   Implement testGetLastMsg().
     */
    public function testGetLastMsg() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::getLog
     * @todo   Implement testGetLog().
     */
    public function testGetLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::getLogHtml
     * @todo   Implement testGetLogHtml().
     */
    public function testGetLogHtml() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::ErrorMsg
     * @todo   Implement testErrorMsg().
     */
    public function testErrorMsg() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::setSqlAutoLog
     * @todo   Implement testSetSqlAutoLog().
     */
    public function testSetSqlAutoLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::setSqlLogModifyingQuery
     * @todo   Implement testSetSqlLogModifyingQuery().
     */
    public function testSetSqlLogModifyingQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::setLogFilename
     * @todo   Implement testSetLogFilename().
     */
    public function testSetLogFilename() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::setSqlLogging
     * @todo   Implement testSetSqlLogging().
     */
    public function testSetSqlLogging() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::getFirstRecordSetFields
     * @todo   Implement testGetFirstRecordSetFields().
     */
    public function testGetFirstRecordSetFields() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::queryToCSV
     * @todo   Implement testQueryToCSV().
     */
    public function testQueryToCSV() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PeerPGDBConnection::niceName
     * @todo   Implement testNiceName().
     */
    public function testNiceName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
