<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-05-25 at 12:42:09.
 */
class SearchQueryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SearchQuery
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SearchQuery;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SearchQuery::setQueryExtension
     * @todo   Implement testSetQueryExtension().
     */
    public function testSetQueryExtension() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::getQueryExtension
     * @todo   Implement testGetQueryExtension().
     */
    public function testGetQueryExtension() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::getLog
     * @todo   Implement testGetLog().
     */
    public function testGetLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::getRelPrefix
     * @todo   Implement testGetRelPrefix().
     */
    public function testGetRelPrefix() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::setRelation
     * @todo   Implement testSetRelation().
     */
    public function testSetRelation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::setKeyColumns
     * @todo   Implement testSetKeyColumns().
     */
    public function testSetKeyColumns() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::areKeyColumnsSet
     * @todo   Implement testAreKeyColumnsSet().
     */
    public function testAreKeyColumnsSet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::setNameExpression
     * @todo   Implement testSetNameExpression().
     */
    public function testSetNameExpression() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::setSubmitValueSet
     * @todo   Implement testSetSubmitValueSet().
     */
    public function testSetSubmitValueSet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::setAuxColNames
     * @todo   Implement testSetAuxColNames().
     */
    public function testSetAuxColNames() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::setOrderList
     * @todo   Implement testSetOrderList().
     */
    public function testSetOrderList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::setDBConn
     * @todo   Implement testSetDBConn().
     */
    public function testSetDBConn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::isRegex
     * @todo   Implement testIsRegex().
     */
    public function testIsRegex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::getWhereList
     * @todo   Implement testGetWhereList().
     */
    public function testGetWhereList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::getQueryTail
     * @todo   Implement testGetQueryTail().
     */
    public function testGetQueryTail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::getQueryHead
     * @todo   Implement testGetQueryHead().
     */
    public function testGetQueryHead() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::getQuery
     * @todo   Implement testGetQuery().
     */
    public function testGetQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::setSubRel
     * @todo   Implement testSetSubRel().
     */
    public function testSetSubRel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::setSubRelJoinColumns
     * @todo   Implement testSetSubRelJoinColumns().
     */
    public function testSetSubRelJoinColumns() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::getExtendedQuery
     * @todo   Implement testGetExtendedQuery().
     */
    public function testGetExtendedQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::getAllQuery
     * @todo   Implement testGetAllQuery().
     */
    public function testGetAllQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::getSubRelQuery
     * @todo   Implement testGetSubRelQuery().
     */
    public function testGetSubRelQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchQuery::subRelExpression
     * @todo   Implement testSubRelExpression().
     */
    public function testSubRelExpression() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
